export const dataSkills = [
    {
        id: 1,
        image: "/svgs/javascript-original.svg",
        alt: "Linguagem de Programação JavaScript",
        href: "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript",
        name: "JavaScript",
    },
    {
        id: 2,
        image: "/svgs/html5-original.svg",
        alt: "Linguagem de Marcação HTML",
        href: "https://developer.mozilla.org/pt-BR/docs/Web/HTML",
        name: "HTML",
    },
    {
        id: 3,
        image: "/svgs/css3-original.svg",
        alt: "Linguagem de Estilização CSS",
        href: "https://developer.mozilla.org/pt-BR/docs/Web/CSS",
        name: "CSS",
    },
    {
        id: 4,
        image: "/svgs/bootstrap-original.svg",
        alt: "Framework CSS Bootstrap",
        href: "https://getbootstrap.com/",
        name: "Bootstrap",
    },
    {
        id: 5,
        image: "/svgs/react-original.svg",
        alt: "Biblioteca JavaScript React.JS",
        href: "https://react.dev/",
        name: "React.JS",
    },
    {
        id: 6,
        image: "/svgs/nextjs-original.svg",
        alt: "Framework JavaScript Next.JS",
        href: "https://nextjs.org/",
        name: "Next.JS",
    },
    {
        id: 7,
        image: "/svgs/typescript-original.svg",
        alt: "Linguagem de Programação TypeScript",
        href: "https://www.typescriptlang.org/",
        name: "TypeScript",
    },
    {
        id: 8,
        image: "/svgs/tailwindcss-original.svg",
        alt: "Framework CSS TailwindCSS",
        href: "https://tailwindcss.com/",
        name: "Tailwind CSS",
    },
    {
        id: 9,
        image: "/svgs/csharp-original.svg",
        alt: "Linguagem de Programação C-Sharp",
        href: "https://dotnet.microsoft.com/pt-br/languages/csharp",
        name: "C-Sharp",
    },
    {
        id: 10,
        image: "/svgs/java-original.svg",
        alt: "Linguagem de Programação Java",
        href: "https://docs.oracle.com/en/java/",
        name: "Java",
    },
    {
        id: 11,
        image: "/svgs/nodejs-original.svg",
        alt: "Runtime JavaScript - Node.JS",
        href: "https://nodejs.org/en",
        name: "Node.JS",
    }
]